### ISSUE TITLE
[FEATURE] Build the Options Page

### ISSUE THREAD

**Issue by prakhartiwari0** [prakhartiwari0/my-web-shortcuts#28]
**Description**
There are a lot of necessary Settings that are not available yet. This issue will address the most required ones and they will be implemented one by one. The Layout also needs to be built.

**Tasks**
- [x] Build a basic Layout with some important links like Report a Bug, Discord Server Link for Support, GitHub Repo link, Webstore link for rating, etc. Plan how different settings will be grouped and divided.
- [x] Create a Shortcuts List where one can see shortcuts for each URL. They will be collapsed/hidden by default and can be expanded/made visible by the user for each URL. 
- [x] The Shortcuts List will have the options to -
   - [x] Delete a URL
   - [x] Delete a Shortcut
   - [x] Enable/Disable a URL
   - [x] Enable/Disable a Shortcut
   - [x] Edit Shortcut Name
   - [x] Edit Shortcut Key

**Comment by prakhartiwari0** [comment]
This issue has been solved with this commit: https://github.com/prakhartiwari0/my-web-shortcuts/commit/81815a49402341d9bd1625e188058673d4f019e0

The Basic layout for Options page has been built, and the basic functionalities are there. It still needs a lot of improvements and feature additions.
